# 2.张量简介与创建

## Tensor概念

Q:张量是什么？
- 一个多维数组，它是标量、向量、矩阵的高维拓展
- ![](http://anki190912.xuexihaike.com/20200918142143.png?imageView2/2/h/150)

Q:Pytorch中的Variable是什么？与Tensor的关系是什么？
- Variable是torch.autograd中的数据类型主要用于封装Tensor，进行自动求导
- data:被包装的Tensor
- grad:data的梯度
- grad_fn:创建Tensor的Function，是自动求导的关键
- requires_grad:指示是否需要梯度
- is_leaf:指示是否是叶子结点（张量）
- ![](http://anki190912.xuexihaike.com/20200918143346.png?imageView2/2/w/200)

Q:Pytorch中的Tensor是什么？
- PyTorch 0.4.0开始，Variable并入Tensor
- dtype: 张量的数据类型，如torch.FloatTensor, torch.cuda.FloatTensor
- shape: 张量的形状，如（64，3， 224， 224）
- device: 张量所在设备，GPU/CPU，是加速的关键
- ![](http://anki190912.xuexihaike.com/20200918143722.png?imageView2/2/h/100)

## Tensor创建

Q:Tensor的函数原型是怎样？
- torch.tensor(data, dtype=None, device=None, requires_grad=False, pin_memory=False)
- 功能：从data创建tensor
- data: 数据，可以是list，numpy
- dtype: 数据类型，默认与data一致
- device: 所在设备，cuda/cpu
- requires_grad: 是否需要梯度
- pin_memory:是否存于锁页内存

Q:通过torch.tensor创建Tensor的代码是什么？

In [4]:
import torch
import numpy as np

arr = np.ones((3, 3))
print(arr)
print('ndarray的数据类型:', arr.dtype)

t = torch.tensor(arr)
print(t)

# 放到gpu上
t = torch.tensor(arr, device='cuda')
print(t)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
ndarray的数据类型: float64
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0', dtype=torch.float64)


Q:如何通过torch.from_numpy创建张量？
- 函数原型：torch.from_numpy(ndarray)
- 功能：从numpy创建tensor
- 注意事项：从torch.from_numpy创建的tensor于原ndarray共享内存，当修改其中一个的数据，另外一个也将会被改动
- ![](http://anki190912.xuexihaike.com/20200918151039.png?imageView2/2/h/150)

In [9]:
arr = np.array([[1,2,3],[4,5,6]])
t = torch.from_numpy(arr)
print("numpy array:")
print(arr)
print("tensor:")
print(t)

print("修改arr:")
arr[0, 0] = 0
print("numpy array:")
print(arr)
print("tensor:")
print(t)

print("修改tensor:")
arr[1, 1] = -10
print("numpy array:")
print(arr)
print("tensor:")
print(t)

numpy array:
[[1 2 3]
 [4 5 6]]
tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
修改arr:
numpy array:
[[0 2 3]
 [4 5 6]]
tensor:
tensor([[0, 2, 3],
        [4, 5, 6]])
修改tensor:
numpy array:
[[  0   2   3]
 [  4 -10   6]]
tensor:
tensor([[  0,   2,   3],
        [  4, -10,   6]])


Q:如何通过torch.zeros或torch.ones创建张量？
- 函数原型：torch.zeros(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
- 函数原型：torch.ones(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
- 功能：依size创建全0张量和全1
- size:张量的形状
- out:输出的张量，貌似其原始类型必须为tensor，通过out得到的和返回值得到的是完全一样的，相当于赋值
- layout:内存中布局形式，有strided,sparse_coo等
- device:所在设备,gpu/cpu
- requires_grad: 是否需要梯度

In [15]:
out_t = torch.tensor([1])
t = torch.zeros((3,3), out=out_t)
print(t)
print(out_t)
print(id(t), id(out_t), id(t) == id(out_t))

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
140055270334752 140055270334752 True


Q:如何通过torch.zeros_like或torch.ones_like创建张量？
- 函数原型：torch.zeros_like(input, dtype=None, layout=None, device=None, requires_grad=False)
- 函数原型：torch.ones_like(input, dtype=None, layout=None, device=None, requires_grad=False)
- 功能：依input形状创建全0张量或全1，input是一个tensor类型
- input:创建与input同形状的全0张量

In [17]:
t = torch.empty(2,3)
print(torch.zeros_like(t))
print(torch.ones_like(t))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


Q:如何通过torch.full创建张量？
- torch.full(size, fill_value, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
- torch.full_like(input, fill_value, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, memory_format=torch.preserve_format)
- 功能：创建全等张量
- size: 张量的形状，如（3,3）
- fill_value: 张量的值

In [22]:
torch.full((3,3), 8)

tensor([[8., 8., 8.],
        [8., 8., 8.],
        [8., 8., 8.]])

Q:如何通过torch.arange创建等差数列的1维张量？
- 函数原型：torch.arange(start=0, end, step=1, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
- 功能：创建等差为1的张量
- 注意事项：数值区间为[start, end)
- start: 数列起始值
- end: 数列“结束值”
- step: 数列公差，默认为1

In [23]:
torch.arange(2,10,2)

tensor([2, 4, 6, 8])

Q:如何通过torch.linspace创建均分数列张量
- 函数原型：torch.linspace(start=0, end, steps=100, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
- 功能：创建均分的1维张量
- 注意事项：数值区间为[start, end]
- start: 数列起始值
- end: 数列结束值
- steps: 数列长度
- 步长为：(end-start)/(steps-1)

In [24]:
torch.linspace(2, 10, 7)

tensor([ 2.0000,  3.3333,  4.6667,  6.0000,  7.3333,  8.6667, 10.0000])

Q:如何通过torch.logspace创建对数均分的1维张量？
- 函数原型：torch.logspace(start, end, steps=100, base=10.0, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
- 功能：创建对数均分的1维张量
- 注意事项：长度为steps，底为base
- base: 对数函数的低，默认为10

Q:如何通过torch.eye创建单位对角矩阵？
- 函数原型：torch.eye(n, m=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
- 功能：创建单位对角矩阵（2维张量）
- 注意事项：默认为方阵
- n: 矩阵行数
- m: 矩阵列数

Q:如何通过torch.normal生成正态分布的张量？
- 函数原型：torch.normal(mean, std, *, generator=None, out=None)
- 功能：生成正态分布（高斯分布）
- mean: 均值
- std: 标准差
- 因mean和std可以分别为标量和张量，有4种不同的组合

In [27]:
# mean：张量 std: 张量
# 其中t[i]是从mean[i],std[i]的标准正态分布中采样得来
mean = torch.arange(1, 5, dtype=torch.float)
std = torch.arange(1, 5, dtype=torch.float)
t = torch.normal(mean, std)
print("mean:{}\nstd:{}".format(mean, std))
print(t)
print()

# mean：标量 std: 标量，此时要指定size大小
t_normal = torch.normal(0., 1., size=(4,))
print(t_normal)
print()

# mean：张量 std: 标量
mean = torch.arange(1, 5, dtype=torch.float)
std = 1
t_normal = torch.normal(mean, std)
print("mean:{}\nstd:{}".format(mean, std))
print(t_normal)

mean:tensor([1., 2., 3., 4.])
std:tensor([1., 2., 3., 4.])
tensor([ 1.3656,  2.6678, -0.7582, 10.2440])

tensor([-1.4877, -0.6809, -1.2212, -1.1693])

mean:tensor([1., 2., 3., 4.])
std:1
tensor([-0.8548,  3.4765,  1.8932,  3.9761])


Q:如何创建标准正态分布的张量？
- torch.randn(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor
- torch.randn_like(input, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format) → Tensor
- size:张量的形状

In [28]:
print(torch.randn(4))
print(torch.randn(2,3))

tensor([ 0.3111, -0.0802,  0.1347,  1.2559])
tensor([[-1.3748,  1.7157, -0.4223],
        [ 1.1199, -1.3477,  0.6594]])


Q:如何生成均匀分布和整数均匀分布的张量？
- 在[0,1)区间上，生成均匀分布
- torch.rand(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor
- torch.rand_like(input, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format) → Tensor
- 在[low, high)区间生成整数均匀分布
- torch.randint(low=0, high, size, *, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor
- torch.randint_like(input, low=0, high, dtype=None, layout=torch.strided, device=None, requires_grad=False, memory_format=torch.preserve_format) → Tensor
- 其中size是张量形状

Q:如何生成从0到n-1的随机排列？
- torch.randperm(n, out=None, dtype=torch.int64, layout=torch.strided, device=None, requires_grad=False) → LongTensor
- n是张量的长度
- 经常用于生成乱序索引

Q:如何生成一个伯努利分布的张量？
- torch.bernoulli(input, *, generator=None, out=None) → Tensor
- 以input为概率，生成伯努利分布（0-1分布，两点分布）

# 3.张量操作与线性回归
